from currency_converter import CurrencyConverter 
import tkinter as tk 
a= CurrencyConverter() 
window=tk.Tk() 
window.geometry("3000x900") 
def cilcked(): 
amount=int(e1.get()) 
cur1=e2.get() 
cur2=e3.get() 
data=a.convert(amount,cur1,cur2) 
l5=tk.Label(window,text=data,font="Times 22 bold").place(x=350,y=650) 
typ1=tk.Label(window,text="ALBANIA--ALL    LEK \n ALGERIA--DZD    DINAR \n AUSTRALIA-AUD    DOLLOR \n AUSTRIA--EUR   EURO\n BELGIUM--EUR   EURO\n BRAZIL--BRL   REAL\nBULGERIA-BGN   LEV\n CANADA--CAD   DOLLOR\nCHILE--CLP   PESO\n CHINA--CNY   YUAN\nDENMARK-DKK   KRONER\nEGYPT--EGP   POUND\n FRANCE--EUR   EURO\n GERMANY--EUR   EURO\n GREESE-EUR   EURO\n GREEN LAND--DKK   DANISH KRONE\n HONG KONG--HKD   DOLLOR\n",font='Times 13 bold').place(x=800,y=100) 
typ2=tk.Label(window,text= "INDIA--INR   RUPEE\n INDONESIA--IDR   RUPIAH\n IRAQ-IQD   DINAR\nITALY--EUR   EURO\nJAPAN--JPY   YEN\n KOREA--KRW   WON\nKUWAIT--KWD   DINAR\n MALAYSIA--MYR   RINGGIT\nMYANMAR--MMK   KYAT\nNEW ZEALAND--NZD   DOLLOR\n NORWAY-NOK   KRONER\nPAKISTAN--PKR   RUPEE\n PHILIPPINS--PHP   PESO\nPORTUGAL-EUR   EURO\nQATAR--QAR   RIYAL\n RUSSIA--RUB   RUBLE\n SOUTH AFRICA--ZAR   RAND\nSPAIN-EUR   EURO\nSRI LANKA--LKR   RUPEE\nTHAILAND--THB   BAHT\nTURKEY--TRY   LIRA\n UKRIAN-UAH   HRYVNIA\nUK--GBP   STERLING\nUS--USD   DOLLOR\n VIETNAM--VND   DONG\n ZIMBABWE-"ZWD   DOLLOR",font='Times 13 bold').place(x=1200,y=100) 
)typ3=tk.Label(window,text="REFERENCE",font="Times 20 bold").place(x=1100,y=20) 
l1=tk.Label(window,text="CURRENCY CONVERTER",font="Times 25 bold").place(x=80,y=30) 
l2=tk.Label(window,text="Enter amount here:",font="Times 20 bold").place(x=150,y=200) 
e1=tk.Entry(window,) 
l3=tk.Label(window,text="Enter currency:",font="Times 20 bold").place(x=150,y=300) 
e2=tk.Entry(window) 
l4=tk.Label(window,text="Enter req. currency:",font="Times 20 bold").place(x=150,y=400) 
e3=tk.Entry(window) 
b1=tk.Button(window,text="CONVERT",command=cilcked,).place(x=350,y=550) 
e1.place(x=450,y=215) 
e2.place(x=450,y=315) 
e3.place(x=450,y=415) 
window.mainloop() 